/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "carre.h"
#include"math.h"

void *
calnull_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
	printf("connexion établie \n");
	return (void *) &result;
}

int *
car_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	result = (*argp)*(*argp) ;

	return &result;
}

double *
rac_1_svc(int *argp, struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	result =sqrt(*argp);
	
	return &result;
}
